
1. Use * to repeat the list [10, 1, 3.3] FIVE times

In [29]:
my_list = [10, 1, 3.3]
repeated_list = my_list * 5
print(repeated_list)

[10, 1, 3.3, 10, 1, 3.3, 10, 1, 3.3, 10, 1, 3.3, 10, 1, 3.3]


2. Use the in operator to check if 3 is inside a list [1, 2, 3, 4, 5]

In [28]:
my_list = [1, 2, 3, 4, 5]
is_three_present = 3 in my_list
print(is_three_present)

True


3. Now look at strings x = 'This is a string'
   
	(a) print first character

	(b) print first two characters

	(c) Print the last element of the string.

	(d) Print 4th element from the end and stop before the 2nd element from the end.

	(e) Slice starting from the 4th element from the end and stopping before the 4nd element from the end.

	(f) Slice from the beginning of the string and stopping before the 3rd element.
  
	(g) Slice starting from the 4th element of the string and going all the way to the end.

In [12]:
#a)
X = 'This is a string'
print(X[0])

T


In [5]:
#b)
print(X[0:2])

Th


In [7]:
#c)
print(X[-1])

g


In [8]:
#d)
print(X[-4:-2])

ri


In [15]:
#e)
sliced_string = X[-4:-4]
print(sliced_string)


In [16]:
#f)
sliced_string = X[0:3]
print(sliced_string)

Thi


In [17]:
#g)
sliced_string = X[4:]
print(sliced_string)

 is a string


4. firstname = 'Arockiaraj'
   lastname = 'S'

	print concatenate firstname and lastname

	print whether 'rock' is present in firstname.

In [18]:
firstname = 'Arockiaraj'
lastname = 'S'
print(firstname + lastname)
print('rock' in firstname)

ArockiarajS
True


5. Split returns a list of all the words in a string, or a list split on a specific character.

	name = 'Tom Mitchell Machine Learning Scientist'.split(' ')


	(a) selects the first element of the list
	(b) selects the last element of the list
	(c) print the firstname
	(d) print middlename
	(e) print lastname
	(f) print firstname + ' ' + middlename+ ' ' + lastname

In [19]:
name = 'Tom Mitchell Machine Learning Scientist'.split(' ')

In [20]:
#a)
print(name[0])

Tom


In [21]:
#b)
print(name[-1])

Scientist


In [22]:
#c)
print(name[0])

Tom


In [23]:
#d)
print(name[1])

Mitchell


In [24]:
#e)
print(name[2:])

['Machine', 'Learning', 'Scientist']


In [27]:
#f)
print(name[0] + ' ' + name[1] + ' ' + name[2])

Tom Mitchell Machine


6. Concatenate the following.

  Chris & 2

In [30]:
L1 = 'Chris'
L2 = 2
print(L1 + str(L2))

Chris2


7. Consider the dictionaries associate keys with values.

  x = {'Arockiaraj': 'araj.s@manipal.edu', 'Bill Gates': 'billg@microsoft.com'}
   

  (a) Retrieve a value by using the indexing operator

  (b) Iterate over all of the keys

  (c) Iterate over all of the values

  (d) Iterate over all of the items in the list

In [31]:
x = {'Arockiaraj': 'araj.s@manipal.edu', 'Bill Gates': 'billg@microsoft.com'}

In [32]:
#a)
print(x['Arockiaraj'])

araj.s@manipal.edu


In [33]:
#b)
for key in x:
    print(key)

Arockiaraj
Bill Gates


In [34]:
#c)
for value in x.values():
    print(value)

araj.s@manipal.edu
billg@microsoft.com


In [35]:
#d)
for item in x.items():
    print(item)

('Arockiaraj', 'araj.s@manipal.edu')
('Bill Gates', 'billg@microsoft.com')


8. Unpack a sequence into different variables: fname, lname, email

  x = ('Arockiaraj', 'Simiyon', 'araj.s@manipal.edu')

In [41]:
x = ('Arockiaraj', 'Simiyon', 'araj.s@manipal.edu')
fname = x[0]
lname = x[1]
email = x[2]
print(fname)
print(lname)
print(email)

Arockiaraj
Simiyon
araj.s@manipal.edu


9. Make sure the number of values you are unpacking matches the number of variables being assigned.

  x = ('Arockiaraj', 'Simiyon', 'araj.s@manipal.edu', 'Manipal')
	fname, lname, email, mname = x

In [39]:
x = ('Arockiaraj', 'Simiyon', 'araj.s@manipal.edu', 'Manipal')
fname, lname, email, mname = x
print(fname)
print(lname)
print(email)
print(mname)

Arockiaraj
Simiyon
araj.s@manipal.edu
Manipal


10. Python has a built in method for convenient string formatting.
	Explain the output of the following code.  

	sales_record = {'price': 3.24, 'num_items': 4, 'person': 'Arockiaraj', 'email':'araj.s@manipal.edu'}

	sales_statement = '{} bought {} item(s) at a price of INR {} each for a total of INR {}'

	print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

In [42]:
sales_record = {'price': 3.24, 'num_items': 4, 'person': 'Arockiaraj', 'email':'araj.s@manipal.edu'}

sales_statement = '{} bought {} item(s) at a price of INR {} each for a total of INR {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

Arockiaraj bought 4 item(s) at a price of INR 3.24 each for a total of INR 12.96


11. Date and time use

	import datetime as dt
	import time as tm

	#time returns the current time in seconds since the Epoch. (January 1st, 1970)

	tm.time()

	from datetime import date
	today = date.today()
	print('today date is', today)

	#Convert the timestamp to datetime.
	dtnow = dt.datetime.fromtimestamp(tm.time())
	dtnow

	#Handy datetime attributes:
	dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

	#timedelta is a duration expressing the difference between two dates.
	delta = dt.timedelta(days = 100) # create a timedelta of 100 days

	#date.today returns the current local date.

	today = dt.date.today()

	today - delta # the date 100 days ago
	today > today-delta # compare dates

In [44]:
import datetime as dt
import time as tm

In [45]:
tm.time()

1728304306.2254858

In [46]:
from datetime import date
today = date.today()
print('today date is', today)

today date is 2024-10-07


In [47]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2024, 10, 7, 12, 32, 38, 244353)

In [48]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2024, 10, 7, 12, 32, 38)

In [49]:
delta = dt.timedelta(days = 100)

In [50]:
date.today

<function date.today>

In [51]:
today = dt.date.today()

In [52]:
today - delta

datetime.date(2024, 6, 29)

12. Objects and map()

#An example of a class in python:

class Person:
    institute = 'Manipal School of Information Sciences' #a class variable

    #self keyword to access the attributes and methods of the class
    
    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):  
        self.location = new_location

person = Person()
person.set_name('Arockiaraj')
person.set_location('Manipal, Udupi, Karnataka')

#what will be the output of the following statement:
print('{} lives in {} and works in the institute {}'.format(person.name, person.location, person.institute))

In [57]:
class Person:
    institute = 'Manipal School of Information Sciences'  # Class variable

    def set_name(self, new_name):
        self.name = new_name

    def set_location(self, new_location):
        self.location = new_location


person = Person()

person.set_name('Arockiaraj')
person.set_location('Manipal, Udupi, Karnataka')

print('{} lives in {} and works in the institute {}'.format(person.name, person.location, person.institute))

Arockiaraj lives in Manipal, Udupi, Karnataka and works in the institute Manipal School of Information Sciences



13. Example set
	x={1, 'x', 2, 'y', (1, 2, 3), 'hello'}
	y = (1, 2, 3)

	#sets are unordered
	y={1, 'x', 2, 'y'}
	z={1, 'x', 2, 'y'}
	print(y, z)

	#Write the output of the after executing the following commands:
	y.add(4)
	z.add('a')
	print(y, z)

In [58]:
x={1, 'x', 2, 'y', (1, 2, 3), 'hello'}
y = (1, 2, 3)

In [59]:
y={1, 'x', 2, 'y'}
z={1, 'x', 2, 'y'}
print(y, z)

{1, 2, 'y', 'x'} {1, 2, 'y', 'x'}


In [60]:
y.add(4)
z.add('a')
print(y, z)

{1, 2, 4, 'x', 'y'} {1, 2, 'x', 'a', 'y'}


14. Here's an example of mapping the min function between three lists.
	Milk, water, sugar, tea packet

	store1 = [10.00, 11.00, 12.34, 5.34]
	store2 = [19.00, 10.10, 12.34, 5.01]
	store3 = [15.00, 12.00, 11.00, 6.00]

	cheapest = map(min, store1, store2, store3)
	costly = map(max, store1, store2, store3)

	print(cheapest)

	(a) Iterate through the map object to see the values.
	(b) Iterate through the map object to see the values.

In [64]:
store1 = [10.00, 11.00, 12.34, 5.34]
store2 = [19.00, 10.10, 12.34, 5.01]
store3 = [15.00, 12.00, 11.00, 6.00]
cheapest = map(min, store1, store2, store3)
costly = map(max, store1, store2, store3)

In [65]:
#a) Iterate through the cheapest map object to see the values
print("Cheapest prices:")
for price in cheapest:
    print(price)

Cheapest prices:
10.0
10.1
11.0
5.01


In [66]:
#b)
print("\nCostliest prices:")
for price in costly:
    print(price)


Costliest prices:
19.0
12.0
12.34
6.0


15. Use the following map function to find the square of the numbers

def calculateSquare(n):
    return n*n

numbers = (1, 2, 3, 4)
result = map(calculateSquare, numbers)
print (result)

(a) what will be the output of the following:

for item in result:
    print(item)

In [68]:
def calculateSquare(n):
  return n*n

numbers = (1, 2, 3, 4)
result = map(calculateSquare, numbers)

In [69]:
#a)
for item in result:
  print(item)

1
4
9
16


16. Lambda function is used when you need a function for a short period of time.


	numbers = (1, 2, 3, 4)
	result = map(lambda x: x*x, numbers)

	(a) Iterate through the map object to see the values.

In [70]:
numbers = (1, 2, 3, 4)
result = map(lambda x: x*x, numbers)

In [71]:
#a)
for item in result:
    print(item)

1
4
9
16


17.

	num1 = [4, 5, 6]
	num2 = [5, 6, 7]

	result = map(lambda n1, n2: n1+n2, num1, num2)


	(a) Iterate through the map object to see the values.

In [72]:
num1 = [4, 5, 6]
num2 = [5, 6, 7]

result = map(lambda n1, n2: n1+n2, num1, num2)

In [73]:
#a)
for item in result:
    print(item)

9
11
13


18. Find the output of the following:

people = ['Python Programming Language', 'Computer Lab Test', 'Vinod Scored A', 'Kumar Scored B']

def split_title_and_name(person):
    
    title = person.split()[0]

    lastname = person.split()[-1]

    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))

In [74]:
people = ['Python Programming Language', 'Computer Lab Test', 'Vinod Scored A', 'Kumar Scored B']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

result = list(map(split_title_and_name, people))

print(result)

['Python Language', 'Computer Test', 'Vinod A', 'Kumar B']


19. Show the use of lambda functions

	dx = lambda x: x * 2

	print(dx(10))

In [75]:
dx = lambda x: x * 2

print(dx(10))

20


20.Show the use of lambda functions

	dx = lambda x, y: (x + y)*2

	print(dx(5, 10))

In [76]:
dx = lambda x, y: (x + y)*2

print(dx(5, 10))

30


21. What will be the output of the following

	my_list = [1, 5, 4, 6, 8, 11, 3, 12]

	new_list1 = list(map(lambda x: x * 2 , my_list))

	new_list2 = map(lambda x: x * 2 , my_list)

	print(new_list1)
	print(new_list2)

In [77]:
my_list = [1, 5, 4, 6, 8, 11, 3, 12]

new_list1 = list(map(lambda x: x * 2 , my_list))

new_list2 = map(lambda x: x * 2 , my_list)

print(new_list1)
print(new_list2)

[2, 10, 8, 12, 16, 22, 6, 24]


In [78]:
print(list(new_list2))

[2, 10, 8, 12, 16, 22, 6, 24]


22. Iterate from 0 to 19 and return the even numbers

my_list = []
for number in range(1, 19):
    if number % 2 == 0:
        my_list.append(number)
my_list


Now the same thing but with list comprehension

my_list = [number for number in range(1, 19) if number % 2 == 0]
my_list

In [79]:
my_list = []
for number in range(1, 19):
    if number % 2 == 0:
        my_list.append(number)
my_list

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [80]:
my_list = [number for number in range(1, 19) if number % 2 == 0]
my_list

[2, 4, 6, 8, 10, 12, 14, 16, 18]

23. Write the output of the following function.

def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]

print(times_tables())
print([j*i for i in range(10) for j in range(10)])

In [81]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range(10):
            lst.append(i * j)
    return lst

print(times_tables() == [j * i for i in range(10) for j in range(10)])

print(times_tables())

print([j * i for i in range(10) for j in range(10)])

True
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81]


24. Numerical Python (NumPy): Write the output of the following

import numpy as np
mylist = [1, 2, 3]
x = np.array(mylist)
(a) what will be the value of x

#Pass in a list of lists to create a multidimensional array.
m = np.array([[7, 8, 9],
              [10, 11, 12]])
(b) what will be the value of m
(c) Find the shape of the array m

consider the following code
n = np.arange(0, 30, 2)
(a) write the value of n
(b) Reshape an array n to be 3x5

#linspace returns evenly spaced numbers over a specified interval.
lspace = np.linspace(0, 10, 9)
(a) what will be the output of above code

lspace.resize(3, 3)
(a) what will be the output of above code

#ones returns a new array of given shape and type, filled with ones.
np.ones((5, 4))
(a) what will be the output of above code

#zeros returns a new array of given shape and type, filled with zeros.
np.zeros((2, 3))
(a) what will be the output of above code

#eye returns a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(3)
(a) what will be the output of above code

# numpy.diag() function
import numpy as np

# matrix creation by array input
num = np.matrix([[11, 121, 130],
                 [613 ,34, 13],
                 [514, 50, 16]])

print("Main Diagnol elements : \n", np.diag(num))
print("\nDiagnol elements above main diagnol : \n", np.diag(num, 1) )
print("\nDiagnol elements below main diagnol : \n", np.diag(num, -1))

(a) write the output of above code

In [87]:
import numpy as np

mylist = [1, 2, 3]
x = np.array(mylist)
print(x)

[1 2 3]


In [88]:
m = np.array([[7, 8, 9], [10, 11, 12]])
print(m)

[[ 7  8  9]
 [10 11 12]]


In [89]:
m.shape

(2, 3)

In [92]:
n = np.arange(0, 30, 2)
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [91]:
n_reshaped = n.reshape(3, 5)
print(n_reshaped)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [93]:
lspace = np.linspace(0, 10, 9)
print(lspace)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [94]:
lspace.resize(3, 3)

In [95]:
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [96]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

25. Write the difference between the following two lines

	np.array([1, 2, 3] * 3)
	np.repeat([1, 2, 3], 3)

In [98]:
num = np.matrix([[11, 121, 130],
                  [613 ,34, 13],
                  [514, 50, 16]])

print("Main Diagonal elements : \n", np.diag(num))
print("\nDiagonal elements above main diagonal : \n", np.diag(num, 1))
print("\nDiagonal elements below main diagonal : \n", np.diag(num, -1))

Main Diagonal elements : 
 [11 34 16]

Diagonal elements above main diagonal : 
 [121  13]

Diagonal elements below main diagonal : 
 [613  50]


26. Write the output of the following


	p = np.ones([3, 3], int)


	np.vstack([p, 2*p])

	np.vstack([p, 2*p, 3*p])

	np.hstack([p, 2*p])

	np.hstack([p, 2*p, 3*p])

In [101]:
p = np.ones([3, 3], int)
print(p)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [102]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [103]:
np.vstack([p, 2*p, 3*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [104]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [105]:
np.hstack([p, 2*p, 3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

27. Observe the output of the following

	x=np.array([1, 2, 3])
	y=np.array([4, 5, 6])

	print(x + y)
	print(x - y)

	print(x * y)
	print(x / y)
	print(x**2)

	x.dot(y)

	z = np.array([y, y**2])

	z.T

In [107]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x**2)
x.dot(y)
z = np.array([y, y**2])
print(z.T)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[[ 4 16]
 [ 5 25]
 [ 6 36]]


28. Write the output of the following

	a = np.array([-4, -2, 1, 3, 5])
	a.sum()

	a.max()

	a.min()

	a.mean()

	a.std()  

	a.argmax()

	a.argmin()

In [109]:
a = np.array([-4, -2, 1, 3, 5])

In [110]:
a.sum()

3

In [111]:
a.max()

5

In [112]:
a.min()

-4

In [113]:
a.mean()

0.6

In [114]:
a.std()

3.2619012860600183

In [115]:
a.argmax()

4

In [116]:
a.argmin()

0

29. Consider the following
	s = np.arange(100)

	what will be the output of the following:
	s = np.arange(6)**2

	s[0], s[4], s[-1]

	s[1:5]

In [119]:
s = np.arange(6)**2

s[0], s[4], s[-1]

(0, 16, 25)

In [120]:
s[1:5]

array([ 1,  4,  9, 16])

30. Consider the following
	s = np.arange(13)**2

	what will be the output of the following:
	s[0], s[4], s[-1]
	s[1:5]
	s[-4:]

	s[-5::-2]
	s[-5:-2]

In [121]:
s = np.arange(13)**2

In [123]:
s[0], s[4], s[-1], s[1:5], s[-4:], s[-5::-2], s[-5:-2]

(0,
 16,
 144,
 array([ 1,  4,  9, 16]),
 array([ 81, 100, 121, 144]),
 array([64, 36, 16,  4,  0]),
 array([ 64,  81, 100]))

31. Let's look at a multidimensional array.
	r = np.arange(100)
	r.resize((10, 10))

	what will be the output of
	r

	r[2, 2]

	r[3, 3:6]

	r[:2, :-1]
	r[-1, ::2]

	r[r > 30]

	r[r > 30] = 30
	r

In [126]:
import numpy as np

r = np.arange(100)
r.resize((10, 10))

In [127]:
print(r)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [128]:
print(r[2, 2])

22


In [129]:
print(r[3, 3:6])

[33 34 35]


In [130]:
print(r[:2, :-1])

[[ 0  1  2  3  4  5  6  7  8]
 [10 11 12 13 14 15 16 17 18]]


In [131]:
print(r[-1, ::2])

[90 92 94 96 98]


In [132]:
print(r[r > 30])

[31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78
 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [133]:
r[r > 30] = 30
print(r)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]]


32. Examine the output of the following code part

	#r2 is a slice of r
	r2 = r[:3,:3]
	r2
	#Set this slice's values to zero ([:] selects the entire array)
	r2[:] = 0
	r2

	#r has also been changed!
	r

	#To avoid this, use r.copy to create a copy that will not affect the original array
	r_copy = r.copy()
	r_copy

	#Now when r_copy is modified, r will not be changed.
	r_copy[:] = 10
	print(r_copy, '\n')
	print(r)

In [134]:
import numpy as np
r = np.arange(100)
r.resize((10, 10))
r2 = r[:3, :3]

In [135]:
print("Original r2:")
print(r2)

Original r2:
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]


In [136]:
r2[:] = 0

In [137]:
print("\nModified r2 (set to 0):")
print(r2)


Modified r2 (set to 0):
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [138]:
print("\nOriginal array r after modifying r2:")
print(r)


Original array r after modifying r2:
[[ 0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0 13 14 15 16 17 18 19]
 [ 0  0  0 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [139]:
r_copy = r.copy()

print("\nCopied array r_copy:")
print(r_copy)


Copied array r_copy:
[[ 0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0 13 14 15 16 17 18 19]
 [ 0  0  0 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [140]:
r_copy[:] = 10

print("\nModified r_copy (set to 10):")
print(r_copy)
print("\nOriginal array r after modifying r_copy:")
print(r)


Modified r_copy (set to 10):
[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]]

Original array r after modifying r_copy:
[[ 0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0 13 14 15 16 17 18 19]
 [ 0  0  0 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


33. Iterating Over Arrays
	#Let's create a new 4 by 3 array of random numbers 0-9.
	test = np.random.randint(0, 10, (4,3))
	test

#Iterate by row:
for row in test:
    print(row)

#Iterate by index:
for i in range(len(test)):
    print(test[i])

#Iterate by row and index:
for i, row in enumerate(test):
    print('row', i, 'is', row)

#Use zip to iterate over multiple iterables.
test2 = test**2
test2

for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

In [142]:
import numpy as np
test = np.random.randint(0, 10, (4, 3))
print("Original array test:")
print(test)

Original array test:
[[6 9 5]
 [5 4 0]
 [2 8 0]
 [8 5 4]]


In [143]:
print("\nIterating by row:")
for row in test:
    print(row)


Iterating by row:
[6 9 5]
[5 4 0]
[2 8 0]
[8 5 4]


In [144]:
print("\nIterating by index:")
for i in range(len(test)):
    print(test[i])


Iterating by index:
[6 9 5]
[5 4 0]
[2 8 0]
[8 5 4]


In [145]:
print("\nIterating by row and index:")
for i, row in enumerate(test):
    print('row', i, 'is', row)


Iterating by row and index:
row 0 is [6 9 5]
row 1 is [5 4 0]
row 2 is [2 8 0]
row 3 is [8 5 4]


In [146]:
test2 = test**2
print("\nSquared array test2:")
print(test2)


Squared array test2:
[[36 81 25]
 [25 16  0]
 [ 4 64  0]
 [64 25 16]]


In [147]:
print("\nIterating with zip:")
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)


Iterating with zip:
[6 9 5] + [36 81 25] = [42 90 30]
[5 4 0] + [25 16  0] = [30 20  0]
[2 8 0] + [ 4 64  0] = [ 6 72  0]
[8 5 4] + [64 25 16] = [72 30 20]
