In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)  

[1 2 3 4 5]


In [3]:
reshaped_1d_to_2d = arr_1d.reshape(1, -1)  # Converts to a row vector
print(reshaped_1d_to_2d)   

[[1 2 3 4 5]]


In [4]:
element = arr_1d[2]  # Access the 3rd element (index 2)
print(element)

3


In [5]:
sliced_arr = arr_1d[1:4]  # Extract elements from index 1 to 3
print(sliced_arr)

[2 3 4]


In [6]:
arr_add = arr_1d + 5  # Adds 5 to each element
print(arr_add)

[ 6  7  8  9 10]


In [7]:
arr_mult = arr_1d * 2  # Multiplies each element by 2
print(arr_mult)

[ 2  4  6  8 10]


In [8]:
sum_arr = arr_1d.sum()  # Returns the sum of all elements
print(sum_arr)

15


In [9]:
max_value = arr_1d.max()  # Maximum element
print(max_value)

5


In [10]:
min_value = arr_1d.min()  # Minimum element
print(min_value)

1


In [11]:
mean_value = arr_1d.mean()  # Average of elements
print(mean_value)

3.0


In [12]:
std_dev = arr_1d.std()  # Standard deviation of elements
print(std_dev)

1.4142135623730951


In [13]:
max_index = arr_1d.argmax()  # Index of the max value
print(max_index)

4


In [14]:
min_index = arr_1d.argmin()  # Index of the min value
print(min_index)

0


In [15]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [16]:
element = arr_2d[1, 2]  # Element in 2nd row, 3rd column
print(element)

6


In [17]:
sliced_2d = arr_2d[0:2, 1:3]  # Extract sub-matrix (rows 0-1, cols 1-2)
print(sliced_2d)

[[2 3]
 [5 6]]


In [18]:
transposed = arr_2d.T  # Transpose of the matrix
print(transposed)   

[[1 4]
 [2 5]
 [3 6]]


In [19]:
# Matrix multiplication (dot product)
mat_mult = np.dot(arr_2d, arr_2d.T)  # Multiplies arr_2d by its transpose
print(mat_mult)

[[14 32]
 [32 77]]
