In [1]:
import numpy as np

In [2]:

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [3]:

# Create a 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
# Get shape of the array
shape = arr_2d.shape
print(shape)


(2, 3)


In [5]:
# Reshape an array
reshaped = arr_1d.reshape(5, 1)
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [6]:
# Accessing elements
element = arr_2d[0, 1]  # Element at first row, second column
print(element)


2


In [7]:
# Slicing (from index 1 to 3)
sliced = arr_1d[1:4]
print(sliced)

[2 3 4]


In [8]:
# Element-wise addition
arr_add = arr_1d + 2  # Adds 2 to every element
print(arr_add)


[3 4 5 6 7]


In [9]:
# Element-wise multiplication
arr_mult = arr_1d * 3  # Multiplies each element by 3
print(arr_mult)

[ 3  6  9 12 15]


In [10]:
# Broadcasting: array and scalar
broadcast = arr_2d + 5  # Adds 5 to every element in the 2D array
print(broadcast)

[[ 6  7  8]
 [ 9 10 11]]


In [11]:
# Calculate square root of each element
sqrt_arr = np.sqrt(arr_1d)
print(sqrt_arr)


[1.         1.41421356 1.73205081 2.         2.23606798]


In [12]:
# Calculate exponential of each element
exp_arr = np.exp(arr_1d)
print(exp_arr)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [13]:
# Sum of elements
total_sum = arr_1d.sum()
print(total_sum)


15


In [14]:
# Mean of elements
mean_val = arr_1d.mean()
print(mean_val)


3.0


In [15]:
# Standard deviation
std_dev = arr_1d.std()
print(std_dev)

1.4142135623730951


In [16]:
# Dot product of two arrays
dot_product = np.dot(arr_1d, arr_1d)  # arr_1d . arr_1d
print(dot_product) 

55


In [17]:
# Concatenate two arrays along a specified axis
arr_concat = np.concatenate([arr_1d, arr_1d], axis=0)
print(arr_concat)

[1 2 3 4 5 1 2 3 4 5]


In [18]:
# Stack arrays vertically (along rows)
arr_stack = np.vstack([arr_2d, arr_2d])
print(arr_stack)    


[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [19]:
# Stack arrays horizontally (along columns)
arr_hstack = np.hstack([arr_2d, arr_2d])
print(arr_hstack)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [20]:
# Compare elements with a value (returns a boolean array)
comparison = arr_1d > 2  # Checks if elements are greater than 2
print(comparison)   

[False False  True  True  True]


In [21]:
# Index of the maximum element
max_index = arr_1d.argmax()
print(max_index)

4


In [22]:
# Index of the minimum element
min_index = arr_1d.argmin()
print(min_index)

0


In [23]:
# Create an array of random integers
random_integers = np.random.randint(0, 10, size=(3, 3))
print(random_integers)

[[1 8 9]
 [3 4 3]
 [4 5 3]]


In [24]:
# Create a random array from a normal distribution
random_normal = np.random.randn(3, 3)
print(random_normal)

[[ 0.85845077  0.98162668 -0.46593974]
 [-0.63214677  0.38594669 -0.00439792]
 [ 0.00975472 -1.26920962  0.14894753]]
